name: Build & Push Multi-Arch Docker Image

on:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: 获取上游最新 Release Tag
        id: get_tag
        run: |
          TAG=$(curl -s https://api.github.com/repos/pmkol/mosdns-x/releases/latest \
            | jq -r .tag_name)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: 设置 QEMU（支持多架构模拟）
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送多架构镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mosdns-x:${{ steps.get_tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/mosdns-x:latest
          build-args: |
            MOSDNS_VERSION=${{ steps.get_tag.outputs.tag }}
