name: Build and Publish mosdns-x Docker Image

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release info
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/pmkol/mosdns-x/releases/latest)
          VERSION=$(echo $LATEST_RELEASE | jq -r '.tag_name')
          ASSETS_URL=$(echo $LATEST_RELEASE | jq -r '.assets[].browser_download_url | select(contains("mosdns-linux-amd64.zip"))')
          
          if [ -z "$ASSETS_URL" ]; then
            echo "No amd64 binary found in latest release"
            exit 1
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "ASSETS_URL=$ASSETS_URL" >> $GITHUB_ENV

      - name: Download mosdns binary
        run: |
          wget -O mosdns-linux-amd64.zip "${{ env.ASSETS_URL }}"
          unzip mosdns-linux-amd64.zip
          chmod +x mosdns

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns-x:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns-x:latest
