name: Build and Publish mosdns-x Docker Image

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release info
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/pmkol/mosdns-x/releases/latest)
          VERSION=$(echo $LATEST_RELEASE | jq -r '.tag_name')
          SOURCE_URL=$(echo $LATEST_RELEASE | jq -r '.zipball_url')
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SOURCE_URL=$SOURCE_URL" >> $GITHUB_ENV

      - name: Download and extract source code
        run: |
          echo "Downloading source from: ${{ env.SOURCE_URL }}"
          wget -O source.zip "${{ env.SOURCE_URL }}"
          unzip source.zip
          # 移动解压后的内容到当前目录
          mv pmkol-mosdns-x-*/* . 2>/dev/null || true
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns-x:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns-x:latest
