name: Build & Push Multi-Arch Docker Image

on:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 获取上游最新 Release 信息
        id: get_release
        run: |
          # 获取最新release信息
          RELEASE_INFO=$(curl -s https://api.github.com/repos/pmkol/mosdns-x/releases/latest)
          TAG_NAME=$(echo "$RELEASE_INFO" | jq -r .tag_name)
          
          # 获取各平台二进制文件下载URL
          AMD64_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "mosdns-linux-amd64.zip") | .browser_download_url')
          ARM64_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "mosdns-linux-arm64.zip") | .browser_download_url')
          
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "amd64_url=$AMD64_URL" >> $GITHUB_OUTPUT
          echo "arm64_url=$ARM64_URL" >> $GITHUB_OUTPUT

      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: 构建 AMD64 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mosdns-x:${{ steps.get_release.outputs.tag_name }}-amd64
          build-args: |
            TARGETARCH=amd64
            BINARY_URL=${{ steps.get_release.outputs.amd64_url }}

      - name: 构建 ARM64 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mosdns-x:${{ steps.get_release.outputs.tag_name }}-arm64
          build-args: |
            TARGETARCH=arm64
            BINARY_URL=${{ steps.get_release.outputs.arm64_url }}

      - name: 创建并推送多架构清单
        uses: docker/manifest-tool@v2
        with:
          name: ghcr.io/${{ github.repository_owner }}/mosdns-x
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository_owner }}/mosdns-x:${{ steps.get_release.outputs.tag_name }}-amd64
            ghcr.io/${{ github.repository_owner }}/mosdns-x:${{ steps.get_release.outputs.tag_name }}-arm64
          tags: |
            ${{ steps.get_release.outputs.tag_name }}
            latest
